sudo: required
services:
  - docker

before_install:
  - docker build -t tapu74/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tapu74/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-429455945852"
  bucket_path: "frontend"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"